# RSS Feed Configuration
rss:
  min_post_date: "2024-11-13"  # Format: YYYY-MM-DD
  image_sources:  # Order determines priority
    use_og_image: true
    use_twitter_image: true
    use_wp_post_image: true
    use_first_image: true  # Fallback to first img tag

# Bot Settings
bot:
  check_interval: 600  # seconds
  max_retries: 5
  initial_delay: 10
  posts_to_check: 50  # Number of recent posts to check for duplicates
  include_images: true  # Feature flag to control whether posts include images
  post_format: "{title}\n\nRead more: {link}"  # Supports {title} and {link} placeholders
  duplicate_detection:
    check_database: true  # Always recommended to be true
    check_bluesky_backup: true  # Backup check against recent posts
    auto_sync_to_database: true  # Auto-sync posts found on Bluesky to database

# Logging
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
