[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "atproto>=0.0.55",
    "beautifulsoup4>=4.12.3",
    "bluesky>=1.13",
    "feedparser>=6.0.11",
    "requests>=2.32.3",
]
